### ISSUE TITLE
Album track order is not accurate

### ISSUE THREAD

**Issue by ndellicarpini** [Goldenfreddy0703/plugin.audio.ytmusic.exp#11]
Opening an album with sorting set to "Track" still always shows the album's tracks in alphabetical order, as opposed to the proper order of the tracks.

This was on Windows 10 x64, Kodi 19.4 x64, using yt-music beta 10.

**Comment by Goldenfreddy0703** [comment]
Ok we will take a loot at that soon.

**Comment by Tecko71** [comment]
> Opening an album with sorting set to "Track" still always shows the album's tracks in alphabetical order, as opposed to the proper order of the tracks.
> 
> This was on Windows 10 x64, Kodi 19.4 x64, using yt-music beta 10.

for me on kodi nexus 20.2 same problem

**Comment by fischcode** [comment]
Issue closed as the current version beta 30 of YTMusic.exp shows album tracks in their proper order (tested with Kodi Omega on Windows)
