### ISSUE TITLE
Playlists do not show all songs

### ISSUE THREAD

**Issue by ndellicarpini** [Goldenfreddy0703/plugin.audio.ytmusic.exp#12]
Playlist results seem to have some max limit to the number of songs that are returned, as opposed to opening the whole playlist. I'm not sure how many songs are returned, much it's much lower than Google Play Music's old limit of 1000 songs.

This was on Windows 10 x64, Kodi 19.4 x64, using yt-music beta 10.

**Comment by Goldenfreddy0703** [comment]
Do you by anychance, know the max number of songs? Maybe I can extend that.

**Comment by ndellicarpini** [comment]
The max number of songs doesn't seem consistent for some reason. I tested 3 playlists, all with wildly varying number of songs.

Playlist 1: Actual Length = 1333 | Returned = 93
Playlist 2: Actual Length = 110 | Returned = 98
Playlist 3: Actual Length = 336 | Returned = 101

**Comment by Goldenfreddy0703** [comment]
That's odd, may need to check that soon.
