### ISSUE TITLE
Playback does not start

### ISSUE THREAD

**Issue by vriesm** [Goldenfreddy0703/plugin.audio.ytmusic.exp#14]
I just did setup this plugin on a Raspberry Pi 2, running LibreElec 10.0.3. Setup was flawless, working with the cookie also was no problem at all. The plugin also shows the content of my library. However, it does not playback any song. The spinning wheel of dead appears for every song. Looking in the log I do see this:

https://paste.kodi.tv/upimaqudor.kodi

Any a clue what might be the problem?

**Comment by woernsn** [comment]
Hmm interesting.
From the logs I can't see anything obvious.
What Kodi versions comes with LE 10.0.3?
I can take a look at that but it might take some time as I'm quite busy with personal stuff and work atm.

**Comment by Goldenfreddy0703** [comment]
Holy crap its been a long time @woernsn , good to see you again. 

It's possible that you may have to reconfigure the addon and get a new yt music cookie and all. Try to reconfigure and restart and try again and see if that helps your issue.

**Comment by vriesm** [comment]
> Hmm interesting. From the logs I can't see anything obvious. What Kodi versions comes with LE 10.0.3? I can take a look at that but it might take some time as I'm quite busy with personal stuff and work atm.

19.4 is coming with LE 10.0.3. I just figured out that sometimes playback will start eventually, but I have to wait minutes before it starts playing. Sometimes it will never start playing at all. I already reconfigured it multiple times with new cookies, but everytime the same issues. Can it be that the RPi-2 is just too slow for it?

**Comment by vriesm** [comment]
I can answer my own question. Just tried it on a RPi-4, but the same playback issue occured.

**Comment by fischcode** [comment]
Issue closed because it relates to very old versions - please re-open if the problem still occurs.
