### ISSUE TITLE
Can't install on Kodi 21 Omega

### ISSUE THREAD

**Issue by wyup** [Goldenfreddy0703/plugin.audio.ytmusic.exp#24]
**When** adding repository .zip [https://goldenfreddy0703.github.io/repository.ytmusic-1.0.zip](https://goldenfreddy0703.github.io/repository.ytmusic/repository.ytmusic-1.0.zip) to Kodi, it installs but can't execute it, 'Start' button it's greyed out, and It doesn't apoesr in add-ons menu.
I can't install it either by adding [https://goldenfreddy0703.github.io/repository.ytmusic](https://goldenfreddy0703.github.io/repository.ytmusic) source to File_manager.

**Comment by Goldenfreddy0703** [comment]
Hey so it's probably cause the addon is not compatible with omega yet, I will look into this and see what I can do later today maybe.

**Comment by fischcode** [comment]
Please try again - I did a test installation of Kodi Omega beta 1 on my windows computer yesterday and it would successfully run the app and play a song (the configuration was taken from my existing Nexus installation)
