### ISSUE TITLE
EXP error 

### ISSUE THREAD

**Issue by Tecko71** [Goldenfreddy0703/plugin.audio.ytmusic.exp#26]
Hy I got that exp error after loading library. Library is  also loaded  over and over again. I am running Beta 16.
[kodi_ytm_error.txt](https://github.com/Goldenfreddy0703/plugin.audio.ytmusic.exp/files/12311658/kodi_ytm_error.txt)

**Comment by fischcode** [comment]
Hi - sorry for answering so late: It looks like the playlist you are trying to load contains less data than expected: Do you happen to know the ID of the playlist you were trying to load? It should be in the logfile, just below the part you have been posting. Is it a public playlist? Does the playlist work when you try to open it from the Home menu (available in newer versions)?

**Comment by Tecko71** [comment]
do not use kodi anymore so can not tell you
