### ISSUE TITLE
Repository is empty on Kodi 19.4

### ISSUE THREAD

**Issue by max-mayorov** [Goldenfreddy0703/plugin.audio.ytmusic.exp#28]
Hi,

When I add source with the repository URL - https://goldenfreddy0703.github.io/repository.ytmusic/ - the File Manager shows empty list. Is this project maintained? :)

Kind regards,
Max

**Comment by Goldenfreddy0703** [comment]
Hey so project is barely maintained at this time due how this addon is coded but you should still be able to install it. The repo should have worked and I even went to the repo link and it has my repo.zip in there. Is there a chance that you entered it wrong by any chance?

**Comment by max-mayorov** [comment]
I have looked in the [docs](https://kodi.wiki/view/Add-on_repositories), and it seems it misses addon.xml file and other metadata. I have forked the repo repo :) and will try to add it in the coming days... Let's see if it works out.

**Comment by Goldenfreddy0703** [comment]
Ok odd, tomorrow I will into it.

**Comment by fischcode** [comment]
Just used the repository myself in Kodi on Raspberry Pi 4 - everything worked nicely.

**Comment by rousseldenis** [comment]
@Goldenfreddy0703 coule you add an index.html file to your repository as kodi does not display the zip file when browsing the url? Thanks

**Comment by Goldenfreddy0703** [comment]
Oh yeah I forgot to check on this sense it's almost Christmas. In a little bit today, I will look into this today.

**Comment by Goldenfreddy0703** [comment]
Hey guys, sorry for not checking this very soon but i replicated the issue and got it working on 19.4. Apparently, github bugged itself for some odd reason so i redid the whole repo now and it should be good this time. Again, sorry for the inconvenience and hope ytmusic works well on 19.4. 

Btw @fischcode i have not tested ytmusic in a very long time but you have done a great job making a google sign in page. Its way better then what we originally and its a massive improvement. Thank you for working on this addon and for polishing it,

**Comment by fischcode** [comment]
HiThanks for the credits - though they largely belong to woerns and you who introduced an oauth login for songs only available to Premium members and to sigma67 who recently introduced  osuth support into ytmusicapi. All I did was to join together the loose ends. But I agree that it‘s a great improvement.Thanks to you for your continuous support :-)Wishing you all the best for a happy and successful 2024!Am 24.12.2023 um 20:00 schrieb Goldenfreddy0703 ***@***.***>:﻿
Hey guys, sorry for not checking this very soon but i replicated the issue and got it working on 19.4. Apparently, github bugged itself for some odd reason so i redid the whole repo now and it should be good this time. Again, sorry for the inconvenience and hope ytmusic works well on 19.4.
Btw @fischcode i have not tested ytmusic in a very long time but you have done a great job making a google sign in page. Its way better then what we originally and its a massive improvement. Thank you for working on this addon and for polishing it,
