### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by weekendsource** [Goldenfreddy0703/plugin.audio.ytmusic.exp#33]
I fixed it by changing line 51 in wrapper.py from:

`            if not self._item['artists'] is None:`

to

`            if self._item['artists']:`

**Comment by Goldenfreddy0703** [comment]
Ahhh thank you @weekendsource we will add your fix to it soon. @fischcode if you can apply his fix, that would be great.

Thank you

**Comment by fischcode** [comment]
Fixed in [1.0-beta22](https://github.com/Goldenfreddy0703/plugin.audio.ytmusic.exp/releases/tag/1.0-beta22)
@weekendsource Thank you for pointing out this issue. Contributions are always welcome 😃
