### ISSUE TITLE
Auto Update Library not working for new Playlist

### ISSUE THREAD

**Issue by jcjdammers** [Goldenfreddy0703/plugin.audio.ytmusic.exp#38]
Hi,
It seems that "Auto Update Library" is not working (I have this setting enabled).
I created a new playlist in https://music.youtube.com/.
But in the addon YtMusic Library --> Playlist it does not appear. Also not after restart or reboot.
Thanks for your help, regards,
Jeroen.

**Comment by fischcode** [comment]
Hi
Thank you for your input: Maybe the name of the setting is misleading - it only automatically updates the library if you do changes from within the addon. So far, I have no idea how to detect changes that you do in YTMusic Web. Let me know if I have a good idea.
Best regards

**Comment by jcjdammers** [comment]
No worries, I noticed that in the context menu there is an option to trigger a library update from YTMusic. That will do for me.
