### ISSUE TITLE
Nothing playing 

### ISSUE THREAD

**Issue by Rinicko100** [Goldenfreddy0703/plugin.audio.ytmusic.exp#42]
Hello @Goldenfreddy0703 

Music is currently not playing with this addon. It just shows an error message

**Comment by Goldenfreddy0703** [comment]
same here so we may need @fischcode to look into it soon. Thanks

**Comment by fischcode** [comment]
I've created a new release 1.0-beta29 based on pytubefix 6.3.3 which appears to play at least the large majority of songs.

**Comment by jcjdammers** [comment]
release 1.0-beta29 is not auto-updated from your repository, can you please check?

**Comment by Goldenfreddy0703** [comment]
Hey sorry I was not available today will go ahead and update it, thanks

**Comment by jcjdammers** [comment]
thanks,auto update from repo worked now.

**Comment by Rinicko100** [comment]
It's back to not playing for me currently... Is it playing for anyone?

**Comment by Rinicko100** [comment]
> It's back to not playing for me currently... Is it playing for anyone?

Is Youtube doing something to stop the addon?

**Comment by jcjdammers** [comment]
Same for me, not playing anymore :-(

**Comment by fischcode** [comment]
Please test the modified cipher.py and release if working - it's experimental but appears to help.
