### ISSUE TITLE
Nothing is playing

### ISSUE THREAD

**Issue by jcjdammers** [Goldenfreddy0703/plugin.audio.ytmusic.exp#43]
Hi,
At the moment no songs are playing for me anymore.
Can you check please?
Thanks.

**Comment by Rinicko100** [comment]
> Hi,
> At the moment no songs are playing for me anymore.
> Can you check please?
> Thanks.

I also have the same issue... nothing currently playing

**Comment by fischcode** [comment]
If uploaded what could be a next release - please let me know if there are still songs which do not play

**Comment by Rinicko100** [comment]
> I've uploaded what could be a next release - please let me know if there are still songs which do not play

Hello sir, has the update been added? it's still on the previous version

**Comment by AndrewNNZ** [comment]
That seems to have fixed it thanks.

**Comment by fischcode** [comment]
New release  [1.0-beta31](https://github.com/Goldenfreddy0703/plugin.audio.ytmusic.exp/releases/tag/1.0-beta31) is out.

**Comment by jcjdammers** [comment]
Is it also available in your Kodi repo, so it will auto update?
Thanks.

**Comment by fischcode** [comment]
Repo has been updated last night: Thanks a lot, @Goldenfreddy0703 !
