### ISSUE TITLE
Add YouTube OAuth for "YouTube Music Premium only" videos

### ISSUE THREAD

**Issue by woernsn** [Goldenfreddy0703/plugin.audio.ytmusic.exp#6]
I came across a case where YouTube cannot deliver the video, as  "This video is only available to Music Premium members".
For these cases we should finish implementing the YouTube OAuth, which was already started in the code.
At the moment, these songs are simply skipped.
Example: https://www.youtube.com/watch?v=KmGIehzf038
![image](https://user-images.githubusercontent.com/6933385/162588271-32194f23-1813-4f19-a99d-e2d23cc7bf69.png)

**Comment by Goldenfreddy0703** [comment]
Ok, thank for telling me about this. I never seen this before, that is sad but we will be skipping those then.

**Comment by woernsn** [comment]
> Ok, thank for telling me about this. I never seen this before, that is sad but we will be skipping those then.

Actually, I find already some logic dealing with possible YouTube OAuth logic in the plugin.
I will take a look when I have time. This is gonna be a bigger change.
