### ISSUE TITLE
Cannot open an artist from search results

### ISSUE THREAD

**Issue by ndellicarpini** [Goldenfreddy0703/plugin.audio.ytmusic.exp#9]
Trying to click on an artist from a search result usually fails. In my experience, the only times it works is when that result item is from your library, if it is not then an error is thrown when you try and open the artist item in the search results.

Here are my logs: https://pastebin.com/ncTVH7T6. The first error from search results is at 348

This was on Windows 10 x64, Kodi 19.4 x64, using yt-music beta 9.

**Comment by Goldenfreddy0703** [comment]
Ahh, I had that issue back then. In the future, I'm thinking of making the search results separate instead of having them merged together, im sure @woernsn does have a fix for this soon.

**Comment by Goldenfreddy0703** [comment]
Hey @ndellicarpini , sorry it's been a few days but big thanks to @woernsn , he provided a fix for it so give it a try and tell us if it's fixed for you.

**Comment by ndellicarpini** [comment]
Sorry, I just got around to testing v10: [LOG](https://pastebin.com/vg1NDrSP)

So opening an artist from the search results works now; however, the results returned are strange. The albums list on the artist page show the appropriate albums, but the albums are all missing their album art and trying to open one throws an error (see line 830 for an example of that). Albums open and work from the search results, but if you go into an artist from the search results, then open an album: that is when the error occurs. Also, it seems like the songs list on the artist page is always at most 5 entries long, which doesn't make sense for most artists.

**Comment by Goldenfreddy0703** [comment]
That's odd, we may need @woernsn again to see this.

**Comment by fischcode** [comment]
Reworked artist output in more recent releases: If more albums and / or songs are available, they can be accessed from a link on the title Albums and/or Songs.
